#!/bin/bash

#------------------------------------------------------------------------------
# This script starts a Bash shell in a container that will have all of
# the tools and packages necessary to build LilyPond.
#
# NOTE: Before running this command, the image must have been pulled or built.
#
# With the options below, the user's homedir is mounted in the usual place,
# as well as the authorization files so that "sudo" works in the container.

# The user's LilyPond git repo is assumed to be somewhere in the homedir
# so it can be worked on inside or outside of Docker. Changes made elsewhere
# in the container will be lost when the main shell exits (including
# results from "make install").
#------------------------------------------------------------------------------

IMAGE=curtmcd/lilypond-buildenv

sudo docker run -ti --rm \
     -u $(id -u):$(id -g) \
     -v /etc/passwd:/etc/passwd:ro \
     -v /etc/shadow:/etc/shadow:ro \
     -v /etc/group:/etc/group:ro \
     -v $HOME:$HOME \
     -w $HOME \
     $IMAGE
